version: '3'
services:
  db:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "8000:8000"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/noteapp"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment :
            access_key_id: AKIAQRE7IFUOKMFPOYQY
            secret_access_key: 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
            DB_USER: root
            DB_REGION: ap-northeast-1
             # DB_NAME: noteapp
            # DB_PASSWORD: password
            # DB_HOST: db
    
