version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: noteapp
    ports:
      - "5432:5432"

  app:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/noteapp"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: Password
      DB_HOST: db
      DB_NAME: noteapp
      DB_PORT: 5432
